"""catch-up: settings, dedup, review_traces tables

Revision ID: ff2fba0db239
Revises: 64ffdef3405b
Create Date: 2026-06-30 15:09:09.590524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2fba0db239'
down_revision: Union[str, Sequence[str], None] = '64ffdef3405b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_deliveries',
    sa.Column('delivery_id', sa.Text(), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('review_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('thread_ts', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('original_verdict', sa.Text(), nullable=True),
    sa.Column('final_verdict', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('gate_json', sa.Text(), nullable=True),
    sa.Column('created', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_traces_thread', 'review_traces', ['channel', 'thread_ts', 'id'], unique=False)
    op.create_table('reviewed_commits',
    sa.Column('repo_sha', sa.Text(), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('repo_sha')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('reviewed_commits')
    op.drop_index('idx_traces_thread', table_name='review_traces')
    op.drop_table('review_traces')
    op.drop_table('github_deliveries')
    # ### end Alembic commands ###
